In [1]:
import numpy as np

In [17]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [23]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [24]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [27]:
cov=a_centered_sp/(a.shape[0]-1)
cov

2.0

In [28]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])